// Enums de TypeScript para validación en DTOs
// Estos enums corresponden a los valores String en SQLite

export enum UserRoleEnum {
  ADMIN = 'ADMIN',
  DIRECCION = 'DIRECCION',
  COMERCIAL = 'COMERCIAL',
  MARKETING = 'MARKETING',
  ADMINISTRATIVO = 'ADMINISTRATIVO',
}

export enum AreaEnum {
  COMERCIAL = 'COMERCIAL',
  MARKETING = 'MARKETING',
  OPERACIONES = 'OPERACIONES',
  ADMINISTRATIVO = 'ADMINISTRATIVO',
  DIRECCION = 'DIRECCION',
}

export enum OKRPeriod {
  ANUAL = 'ANUAL',
  TRIMESTRAL = 'TRIMESTRAL',
  MENSUAL = 'MENSUAL',
}

export enum KRType {
  NUMERICO = 'NUMERICO',
  PORCENTAJE = 'PORCENTAJE',
  CUALITATIVO = 'CUALITATIVO',
}

export enum LeadSource {
  WEB = 'WEB',
  REFERIDO = 'REFERIDO',
  REDES_SOCIALES = 'REDES_SOCIALES',
  CAMPANA = 'CAMPANA',
  EVENTO = 'EVENTO',
  OTRO = 'OTRO',
}

export enum OpportunityStage {
  PROSPECCION = 'PROSPECCION',
  CALIFICACION = 'CALIFICACION',
  PROPUESTA = 'PROPUESTA',
  NEGOCIACION = 'NEGOCIACION',
  CIERRE = 'CIERRE',
  GANADA = 'GANADA',
  PERDIDA = 'PERDIDA',
}

export enum ActivityType {
  LLAMADA = 'LLAMADA',
  EMAIL = 'EMAIL',
  REUNION = 'REUNION',
  TAREA = 'TAREA',
  NOTA = 'NOTA',
  VISITA = 'VISITA',
}

export enum QuoteStatus {
  BORRADOR = 'BORRADOR',
  ENVIADA = 'ENVIADA',
  ACEPTADA = 'ACEPTADA',
  RECHAZADA = 'RECHAZADA',
  VENCIDA = 'VENCIDA',
}

export enum ContractStatus {
  BORRADOR = 'BORRADOR',
  EN_REVISION = 'EN_REVISION',
  APROBADO = 'APROBADO',
  FIRMADO = 'FIRMADO',
  VIGENTE = 'VIGENTE',
  FINALIZADO = 'FINALIZADO',
  CANCELADO = 'CANCELADO',
}

export enum PaymentStatus {
  PENDIENTE = 'PENDIENTE',
  PARCIAL = 'PARCIAL',
  PAGADO = 'PAGADO',
  VENCIDO = 'VENCIDO',
  CANCELADO = 'CANCELADO',
}

export enum CampaignChannel {
  EMAIL = 'EMAIL',
  REDES_SOCIALES = 'REDES_SOCIALES',
  GOOGLE_ADS = 'GOOGLE_ADS',
  FACEBOOK_ADS = 'FACEBOOK_ADS',
  LINKEDIN = 'LINKEDIN',
  EVENTO = 'EVENTO',
  CONTENIDO = 'CONTENIDO',
  OTRO = 'OTRO',
}

export enum FileType {
  PDF = 'PDF',
  DOCX = 'DOCX',
  XLSX = 'XLSX',
  IMAGEN = 'IMAGEN',
  OTRO = 'OTRO',
}

export enum EntityType {
  QUOTE = 'QUOTE',
  CONTRACT = 'CONTRACT',
  OPPORTUNITY = 'OPPORTUNITY',
  CAMPAIGN = 'CAMPAIGN',
  OTRO = 'OTRO',
}

export enum TaskStatus {
  PENDIENTE = 'PENDIENTE',
  EN_PROGRESO = 'EN_PROGRESO',
  COMPLETADO = 'COMPLETADO',
  BLOQUEADO = 'BLOQUEADO',
}

export enum FeedbackStatus {
  PENDIENTE = 'PENDIENTE',
  EN_REVISION = 'EN_REVISION',
  RESUELTO = 'RESUELTO',
  CERRADO = 'CERRADO',
}

export enum FeedbackProcess {
  OKR = 'OKR',
  CRM = 'CRM',
  COTIZACIONES = 'COTIZACIONES',
  CONTRATOS = 'CONTRATOS',
  MARKETING = 'MARKETING',
  ADMINISTRATIVO = 'ADMINISTRATIVO',
  RECURSOS_HUMANOS = 'RECURSOS_HUMANOS',
  FINANZAS = 'FINANZAS',
  OPERACIONES = 'OPERACIONES',
  OTRO = 'OTRO',
}

